require "core.options"
require "core.lazy"
require "core.keymaps"
require "core.colours"
require "core.cmp"
require "core.lsp"
require "core.treesitter"
require "core.nvim-tree"
require "core.bufferline"
require "core.lualine"
require "core.comment"
require "core.indent-blankline"

require "core.notify"
require "core.noice"
-- require "core.which-key"
require "core.colorizer"
require "core.telescope"

require "core.mason"
require "core.mason-lspconfig"
require "core.conform-nvim"
require "core.mason-nvim-dap"
require "core.nvim-dap-ui"
require "core.rest-nvim"
require "core.nvim-lint"
